# Generated by Django 5.2.7 on 2025-10-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.company'),
        ),
    ]
